# GENCODE_SM50 := 
# GENCODE_SM61 := 
# GENCODE_SM30 := 
# GENCODE_SM35 := 
GENCODE_SM80 := 
GENCODE_SM86 := 

SRC = tensor_sparse_lat_half.cu

EXE = tensor_sparse_lat_half

include ../../../common/common.mk
