GENCODE_SM30 := 
GENCODE_SM35 := 
GENCODE_SM50 := 
GENCODE_SM60 := 
GENCODE_SM62 := 
GENCODE_SM70 := 
GENCODE_SM75 := 

SRC = tensor_mma_lat_half.cu

EXE = tensor_mma_lat_half

include ../../../common/common.mk
